name: Gabung Playlist
on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'  # jalan otomatis tiap jam 0 menit
    # kalau mau tiap 30 menit ganti jadi: '*/30 * * * *'
    # kalau mau tiap jam 17 menit: '17 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests
      - run: python gabung.py
      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add derama/
          git diff --staged --quiet || git commit -m "auto update $(date)"
          git push
