name: Gabung M3U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run gabung.py
        run: python gabung.py

      - name: Commit hasil
        run: |
          git config --global user.name "lian-bot"
          git config --global user.email "bot@lian.com"
          git add derama/hasil.m3u
          git diff --staged --quiet || git commit -m "auto update hasil.m3u via cron-job.org"
          git push
