name: gabung
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests
      - run: python script/gabung.py
      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add derama/hasil.m3u
          git commit -m "update" || true
          git push
